### ISSUE TITLE
Использование std::cerr

### ISSUE THREAD

**Issue by sshaplygin** [PlushBeaver/cs19-lab01#1]
Добрый день, Дмитрий!

Не совсем понятно зачем используется std::cerr для отображения пользовательской информации в следующих строках:

https://github.com/PlushBeaver/cs19-lab01/blob/72dfc0626dcbd62f7909aad7995361420c52d3e7/main.cpp#L10
https://github.com/PlushBeaver/cs19-lab01/blob/72dfc0626dcbd62f7909aad7995361420c52d3e7/main.cpp#L13
https://github.com/PlushBeaver/cs19-lab01/blob/72dfc0626dcbd62f7909aad7995361420c52d3e7/main.cpp#L20

Поясните пожалуйста.
Спасибо!

**Comment by PlushBeaver** [comment]
Здравствуйте. Это для удобства [автоматических тестов в ходе ЛР](http://uii.mpei.ru/study/courses/cs/lab01/#%D0%B0%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F-%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0%D0%BF%D0%BE%D1%8D%D1%82%D0%B0%D0%BB%D0%BE%D0%BD%D0%BD%D0%BE%D0%BC%D1%83-%D0%B2%D0%B2%D0%BE%D0%B4%D1%83-%D0%B8%D0%B2%D1%8B%D0%B2%D0%BE%D0%B4%D1%83): декоративный вывод (stderr) можно легко убрать, а полезный (stdout) можно направить в файл, чтобы затем сравнить с эталоном.

**Comment by sshaplygin** [comment]
@PlushBeaver аааа, понятно зачем это было сделано.
Классно, что студентам дается такой актуальный материал.
Спасибо!
